version: "3"
services:
  postgres:
    image: postgres:13
    container_name: "postgres-knab"
    environment:
      - POSTGRES_DB=knab
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Sao_Paulo
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
       - "5432:5432"
  knab:
    image: knab
    container_name: "knab"
    links:
      - "postgres:postgres"
    depends_on:
      - postgres
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_DBNAME=postgres
      - PG_PORT=5432
      - JWT_KEY=51d7fe292d4883dd6e408542
      - PREST_PORT=8888
      - PREST_HOST=0.0.0.0
      - PREST_MIGRATIONS=./migrations
      - PREST_QUERIES=./queries
    ports:
      - "8888:8888"